---
# tasks to build leaf underlay
- name: Generate ISN Config
  template: src=ISN.j2 dest=roles/ISN/files/{{inventory_hostname}}.cfg

- name: Push ISN Config
  nxos_config:
    src: roles/ISN/files/{{inventory_hostname}}.cfg
    match: none
    provider: "{{ nxos_provider }}"

- name: GATHER FACTS FOR Leaf "{{ inventory_hostname }}"
  nxos_facts:
    provider: "{{ nxos_provider }}"

- debug: var=ansible_net_neighbors

- name: create interface keys
  set_fact:
    interfaces: "{{ ansible_net_neighbors.keys() }}"
- debug: var=interfaces


- name: Configure uplink interfaces to BGW
  nxos_config:
    provider: "{{ nxos_provider }}"
    lines:
      - no switchport
      - mtu 9216
      - medium p2p
      - ip unnumbered loopback0
      - ip ospf network point-to-point
      - ip router ospf EXTERNAL area 0.0.0.0
      - no shutdown
    parents: interface {{ item }}
    match: none
  with_items: "{{ interfaces }}"
  when: ansible_net_neighbors[item][0]["sysname"] is search("BGW")

- name: Ensure an interface to BGW has the proper description
  nxos_interface:
    provider: "{{ nxos_provider }}"
    name: "{{ item }}"
    description: 'Connected-to-{{ ansible_net_neighbors[item][0]["port"] }}-{{ ansible_net_neighbors[item][0]["sysname"] }} '
  with_items: "{{ interfaces}}"
  when: ansible_net_neighbors[item][0]["sysname"] is search("BGW")

- name: Configure uplink interfaces to ISN
  nxos_config:
    provider: "{{ nxos_provider }}"
    lines:
      - no switchport
      - mtu 9216
      - medium p2p
      - ip unnumbered loopback0
      - ip ospf network point-to-point
      - ip router ospf EXTERNAL area 0.0.0.0
      - no shutdown
    parents: interface {{ item }}
    match: none
  with_items: "{{ interfaces }}"
  when: ansible_net_neighbors[item][0]["sysname"] is search("ISN")

- name: Ensure an interface to BGW has the proper description
  nxos_interface:
    provider: "{{ nxos_provider }}"
    name: "{{ item }}"
    description: 'Connected-to-{{ ansible_net_neighbors[item][0]["port"] }}-{{ ansible_net_neighbors[item][0]["sysname"] }} '
  with_items: "{{ interfaces}}"
  when: ansible_net_neighbors[item][0]["sysname"] is search("ISN")
