---
#Task 1: Build the Underlay for all spines
- hosts: leafs
  connection: network_cli
  vars:
    nxos_provider:
      username: "{{ user }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ hostvars[inventory_hostname].ansible_host }}"

  tasks:

    - name: ENSURE port is configured as access port
      nxos_l2_interface:
        provider: "{{ nxos_provider}}"
        name: "{{ item.name }}"
        mode: access
        access_vlan: "{{ item.access_vlan }}"
      with_items:
          - { name: "Ethernet1/3", access_vlan: 103 }
