---
all:
  vars:
    ansible_connection: local
    user: admin
    pwd: C1sc0123!
    gather_fact: no
  
  children:

    # Border gateways Information
    BGW:
      hosts:
        BGW-1:
          hostname: BGW-1
          ansible_host: 10.2.28.103
          lo0_ipaddr: 100.64.0.103
          lo1_ipaddr: 100.64.1.103 
          lo2_ipaddr: 100.64.2.103 
          lo100_ipaddr: 100.64.100.103 
          site_id: 1 
          BGW_To_ISN: 100.64.254.13
          ISN_To_BGW: 100.64.254.14 

        BGW-2:
          hostname: BGW-2
          ansible_host: 10.2.28.104
          lo0_ipaddr: 100.64.0.104 
          lo1_ipaddr: 100.64.1.104 
          lo2_ipaddr: 100.64.2.104 
          lo100_ipaddr: 100.64.100.104 
          site_id: 1 
          BGW_To_ISN: 100.64.254.21 
          ISN_To_BGW: 100.64.254.22 
        
        BGW-3:
          hostname: BGW-3
          ansible_host: 10.2.28.107
          lo0_ipaddr: 100.64.0.107
          lo1_ipaddr: 100.64.1.107 
          lo2_ipaddr: 100.64.2.107 
          lo100_ipaddr: 100.64.100.107 
          site_id: 2 
          BGW_To_ISN: 100.64.254.69 
          ISN_To_BGW: 100.64.254.70
        
        BGW-4:
          hostname: BGW-4
          ansible_host: 10.2.28.108
          lo0_ipaddr: 100.64.0.108
          lo1_ipaddr: 100.64.1.108 
          lo2_ipaddr: 100.64.2.108 
          lo100_ipaddr: 100.64.100.108 
          site_id: 2 
          BGW_To_ISN: 100.64.254.41
          ISN_To_BGW: 100.64.254.42

    # Leafs information 
    leafs:
      hosts:
        Leaf101:
          hostname: Leaf101
          ansible_host: 10.2.28.101
          lo0_ipaddr: 100.64.0.101
          lo1_ipaddr: 100.64.1.101 
          lo2_ipaddr: 100.64.2.101 
          lo100_ipaddr: 100.64.100.101
        
        Leaf102:
          hostname: Leaf102
          ansible_host: 10.2.28.102
          lo0_ipaddr: 100.64.0.102
          lo1_ipaddr: 100.64.1.102 
          lo2_ipaddr: 100.64.2.102 
          lo100_ipaddr: 100.64.100.102

        Leaf105:
          hostname: Leaf105
          ansible_host: 10.2.28.105
          lo0_ipaddr: 100.64.0.105
          lo1_ipaddr: 100.64.1.105 
          lo2_ipaddr: 100.64.2.105 
          lo100_ipaddr: 100.64.100.105

        Leaf106:
          hostname: Leaf106
          ansible_host: 10.2.28.106
          lo0_ipaddr: 100.64.0.106
          lo1_ipaddr: 100.64.1.106 
          lo2_ipaddr: 100.64.2.106 
          lo100_ipaddr: 100.64.100.106