---
#Task 1: Build the Underlay for all Leafs
- hosts: leafs
  connection: local
  roles:
  - spine_underlay

  vars:
    nxos_provider:
      username: "{{ user }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ hostvars[inventory_hostname].ansible_host }}"

  tasks:

    - name: GATHER FACTS FOR Leaf "{{ inventory_hostname }}"
      nxos_facts:
        provider: "{{ nxos_provider }}"

    - debug: var=ansible_net_neighbors

    - name: CREATE INTERFACE KEYS BASED ON CDP INFORMATION
      set_fact:
        interfaces: "{{ ansible_net_neighbors.keys() }}"
    - debug: var=interfaces


    - name: CONFIGURE UPLINK INTERFACES TO SPINES
      nxos_config:
        provider: "{{ nxos_provider }}"
        lines:
          - no switchport
          - mtu 9216
          - medium p2p
          - ip unnumbered loopback0
          - ip ospf network point-to-point
          - ip router ospf UNDERLAY area 0.0.0.0
          - no shutdown
        parents: interface {{ item }}
        match: none
      with_items: "{{ interfaces }}"
      when: ansible_net_neighbors[item][0]["sysname"] is search("Spine")

    - name: CONFIGURE PROPER DISCRIPTION FOR UPLINKS TO LEAFS BASED ON CDP INFORMATION
      nxos_interface:
        provider: "{{ nxos_provider }}"
        name: "{{ item }}"
        description: 'Connected-to-{{ ansible_net_neighbors[item][0]["port"] }}-{{ ansible_net_neighbors[item][0]["sysname"] }} '
      with_items: "{{ interfaces}}"
      when: ansible_net_neighbors[item][0]["sysname"] is search("Spine")
