---
# vars file for jinja2_leaf
  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    timeout: 100
    host: "{{ hostvars[inventory_hostname].ansible_host }}"
  asn: 65000
  router_id: 100.64.0.100
  bgp_neighbors:
    - neighbor: 100.64.0.201
    - neighbor: 100.64.0.202
  L3_interfaces:
    -  interface: Ethernet 1/1
    -  interface: Ethernet 1/2
    -  interface: loopback 0
    -  interface: loopback 1

  vlan_range:
       low: 100
       high: 105

  L2VNI:
    -  vlan_id: 100
       vni: 50100
       ip_add: 172.21.100.1
       mask: 24
       vlan_name: L2-VNI-100-tenant-1
       mcast: 239.0.0.100
    -  vlan_id: 101
       vni: 50101
       ip_add: 172.21.101.1
       mask: 24
       vlan_name: L2-VNI-101-tenant-1
       mcast: 239.0.0.110

  L3VNI:
    -  vlan_id: 999
       vlan_name: L3-VNI-999-Tenant1
       vni: 50999
