---
# vars file for jinja2_leaf
  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    timeout: 100
    host: "{{ hostvars[inventory_hostname].ansible_host }}"

  asn: 65000

  router_id: 100.64.0.100

  bgp_neighbors:
    - neighbor: 100.64.0.201
    - neighbor: 100.64.0.202
