---
nxos_provider:
  username: '{{ user }}'
  password: '{{ pwd }}'
  timeout: 100
  host: '{{ hostvars[inventory_hostname].ansible_host }}'

# vars for creation of l2vni and vlan interface configuration

l2vni:
- ip_address: 192.168.103.254/24
  l2vni: '44103'
  name: L2BD-103
  vlan_id: '103'
  vrf: ' EVPN-L3-VNI-VLAN-1000'
