---
nxos_provider:
  username: '{{ user }}'
  password: '{{ pwd }}'
  timeout: 100
  host: '{{ hostvars[inventory_hostname].ansible_host }}'

# vars for creation of l2vni and vlan interface configuration

l2vni:
- l2vni: '44123'
  name: L2BD-123
  vlan_id: '123'
- l2vni: '44124'
  name: L2BD-124
  vlan_id: '124'
- l2vni: '44125'
  name: L2BD-125
  vlan_id: '125'
- l2vni: '44126'
  name: L2BD-126
  vlan_id: '126'
- l2vni: '44127'
  name: L2BD-127
  vlan_id: '127'
- l2vni: '44128'
  name: L2BD-128
  vlan_id: '128'
- l2vni: '44129'
  name: L2BD-129
  vlan_id: '129'
