---
# vars file for l3vni_overlay

nxos_provider:
  username: '{{ user }}'
  password: '{{ pwd }}'
  timeout: 100
  host: '{{ hostvars[inventory_hostname].ansible_host }}'

# vars for creation of l3vni and vrf creation

l3vni:
  - l3vni: '44999'
    name: L3-VNI-VLAN-999
    vlan_id: '999'

vrf:
  - name: EVPN-L3-VNI-VLAN-999
    l3vni: '44999'

asn: 65000
