---
# vars file for leaf_underlay
  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    timeout: 100
    host: "{{ hostvars[inventory_hostname].ansible_host }}"

  asn_site_1: 65001
  asn_site_2: 65002
  asn_site_3: 65003

  bgp_neighbors_site_1:
    - spine:
      - neighbor: 100.64.0.201
      - neighbor: 100.64.0.202
    
      BGW:
      - neighbor: 100.64.0.103
      - neighbor: 100.64.0.104
  
  bgp_neighbors_site_2:
    - spine:
      - neighbor: 100.64.0.203
      - neighbor: 100.64.0.204
      
      BGW:
      - neighbor: 100.64.0.107
      - neighbor: 100.64.0.108

  bgp_neighbors_site_3:
    - neighbor_spine: 100.64.0.205
    - neighbor_spine: 100.64.0.206

